(define id (lambda (x) x))
(define add (lambda (x y) (+ x y)))
(define fact (lambda (n) (if (= n 0) 1 (* n (fact (+ n -1))))))
(define nested (lambda (x) (lambda (y) (lambda (z) (* z x)))))
((lambda (x) x) 5)
(id 4)
(add 3 4)
;(fact 5)
(((nested 3) 4 ) 5)